PR #1 (initial check)
Sergej-Nishpal/java-explore-with-me pull request #1
Opened 2022-11-13 13:12 UTC by Sergej-Nishpal

feat: создать структуру проекта, настроить Maven и Docker, создать схемы БД, частично создать некоторые классы.

2022-12-01 22:13 UTC, sergeymamonov requested changes

2022-12-01 22:13 UTC, sergeymamonov commented on main/src/main/java/ru/practicum/ewmmain/repository/RequestRepository.java
> +    Collection<ParticipationRequest> findAllByEventId(long eventId);
Здесь действительно необходимо отдавать интерфейс Collection? Это достаточно общий интерфейс, то есть это может быть и массив и множество.

2022-12-01 22:13 UTC, sergeymamonov commented on main/src/main/java/ru/practicum/ewmmain/service/admin/AdminAccessServiceImpl.java
> +        final int hoursBeforeForPublish = 1;
Числа лучше стараться выносить из кода в константы. И давать им информативное название.

2022-12-01 22:13 UTC, sergeymamonov commented on main/src/main/java/ru/practicum/ewmmain/service/any/AnyAccessServiceImpl.java
> +            statClient.save(endpointHitDto);
Здесь мы делаем в цикле запрос к сервису статистики, а это поход по сети, обращение в БД. То есть мы грузим сеть и БД. Постарайтесь обойтись одним запросом.

2022-12-01 22:13 UTC, sergeymamonov commented on main/src/main/java/ru/practicum/ewmmain/service/auth/AuthAccessServiceImpl.java
> +        final int hoursBeforeForUpdateEvent = 2;
Убрать в константу. Посмотрите про антипаттерн "магические числа".

2022-12-01 22:13 UTC, sergeymamonov commented on stat/src/main/java/ru/practicum/ewmstat/service/StatServiceImpl.java
> +        for (String uri : uris) {
А нельзя это сделать на стороне БД?

2022-12-02 14:23 UTC, Sergej-Nishpal commented on main/src/main/java/ru/practicum/ewmmain/repository/RequestRepository.java
> +    Collection<ParticipationRequest> findAllByEventId(long eventId);
Сергей, везде заменил на более "конкретный" List.
Раньше у ревьюеров не было замечаний по этому поводу, поэтому не придавал этому особого значения.
Исправлено.

2022-12-02 14:24 UTC, Sergej-Nishpal commented on main/src/main/java/ru/practicum/ewmmain/service/admin/AdminAccessServiceImpl.java
> +        final int hoursBeforeForPublish = 1;
Вынес, назвал по-другому.
Исправлено.

2022-12-02 14:26 UTC, Sergej-Nishpal commented on main/src/main/java/ru/practicum/ewmmain/service/any/AnyAccessServiceImpl.java
> +            statClient.save(endpointHitDto);
Попробовал передавать в статистику список, но так не принимают тесты Postman.
Уточнил - по этому эндпойнту увеличение просмотров по всем ивентам не требуется, поэтому обращения в цикле просто убрал. Отправляется стандартный просмотр.
Исправлено.

2022-12-02 14:27 UTC, Sergej-Nishpal commented on main/src/main/java/ru/practicum/ewmmain/service/auth/AuthAccessServiceImpl.java
> +        final int hoursBeforeForUpdateEvent = 2;
Убрал, переименовал.
Исправлено.

2022-12-02 14:30 UTC, Sergej-Nishpal commented on stat/src/main/java/ru/practicum/ewmstat/service/StatServiceImpl.java
> +        for (String uri : uris) {
К сожалению, для меня это пока не так просто. :/ Но реализовать удалось.
Выполняется на стороне БД.
Исправлено.

2022-12-02 14:51 UTC, Sergej-Nishpal commented on stat/src/main/java/ru/practicum/ewmstat/service/StatServiceImpl.java
> +        for (String uri : uris) {
Сергей, папки с тестами я оставил, т.к. возможно, успею написать тесты, когда буду заниматься фичей. Это не критично, что она останется? Или лучше убрать?

2022-12-03 04:33 UTC, sergeymamonov commented on stat/src/main/java/ru/practicum/ewmstat/service/StatServiceImpl.java
> +        for (String uri : uris) {
Порекомендовал вам убрать эти папки, на случай, если будут смотреть при приеме на работу ваш код, то чтобы не было такого, что человек полезет в эти папки посмотреть тесты и не найдет их там). Только из-за этого. Поэтому оставлять или не оставлять папки это на ваш выбор.

2022-12-03 04:45 UTC, sergeymamonov approved these changes

2022-12-03 04:45 UTC, sergeymamonov commented on main/src/main/java/ru/practicum/ewmmain/service/admin/AdminAccessServiceImpl.java
> +    private static final int ONE_HOUR_BEFORE_EVENT_DATE = 1;
Писать **ONE**в названии лишнее, это же понятно из числа. А вот написать MIN_HOURS это важнее.

2022-12-03 04:45 UTC, sergeymamonov commented on main/src/main/java/ru/practicum/ewmmain/service/auth/AuthAccessServiceImpl.java
> +    private static final int TWO_HOURS_BEFORE_EVENT_DATE = 2;
Аналогично TWO в названии лишнее, нужно написать что это двойка ограничивает в данном случае, то есть нижнюю границу количества часов. А само число уже будет в константе. Может завтра это число поменяется на 3, не менять же каждый раз название константы.

2022-12-03 12:28 UTC, Sergej-Nishpal commented on main/src/main/java/ru/practicum/ewmmain/service/admin/AdminAccessServiceImpl.java
> +        final int hoursBeforeForPublish = 1;
Назвал корректно.

2022-12-03 12:29 UTC, Sergej-Nishpal commented on main/src/main/java/ru/practicum/ewmmain/service/auth/AuthAccessServiceImpl.java
> +        final int hoursBeforeForUpdateEvent = 2;
Также назвал корректно.

2022-12-03 12:36 UTC, merged